### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [marslayr/agnes-grey#1]
- You have a lot of HTML comments all over the place. You should remove basically all of them, including in se-lint-ignore.xml. Lots of commented out code for some reason.
- All instances of z3998:poem should be changed to z3998:verse, because they are verse fragments and not full poems. The exception is "Oh, they have robbed me of the hope" which appears to be a whole poem. You'll have to add z3998:verse selectors to local.css too. Since the styles are the same, just add those selectors to the existing selectors instead of duplicating all of the rules.
- `se modernize-spelling` makes one change that should be accepted
- `honoured above every one` should be `everyone`
- `se typogrify` makes changes that should be accepted
- `se semanticate` makes changes that should be accepted
- Lots of `<i>` without semantics, which are mostly incorrect. When a word is emphasized, you should use `<em>`. For italics that are not emphasis, like the names of newspapers etc., use the [SE semantic vocabulary](https://standardebooks.org/vocab/1.0). For example, `<i epub:type="se:name.publication.newspaper">Gazette</i>`. See https://standardebooks.org/manual/1.6.4/single-page#8.2 You can speed up the process of changing `<i>` to `<em>` with a clever regex and `se interactive-replace`, making sure not to add `<em>` to words that are italicized, but not emphasized. Once you're done, there should be no plain `<i>` without `epub:type` semantics left in the ebook.
- In se-lint-ignore.xml, your reasons appear to be incorrect - they are unrelated to the errors that lint is bringing to your attention, and also all of those lint errors are correct and must be addressed. t-029 is correct, `cent.` is an abbreviation and requires `<abbr>`. t-042 is correct, there is a wrong space after `‘` in `says he,‘ <abbr>Mr.</abbr>`. Then, you can remove se-lint-ignore.xml.

Metadata:

- dc:description: I don't see how this description is relevant to the plot of the book. Can you rewrite this to be more accurate, in the active voice, and in a way that obviously encapsulates the plot for someone who has never read the book? "A young woman..."
- Empty CONTRIBUTOR_FULL_NAME
- Remove commented out PRODUCTION_NOTES

Once you've done all of this, make sure to run `se lint` one more time.

Your git history contains a lot of commits, changes, and deletions of temporary files, like readmes and lint.txt. For future ebooks, please don't commit that kind of stuff to the ebook repo - it clutters the history with irrelevant information and makes it harder for people to go back and understand what happened to the ebook. You can keep notes that are for your own use and temporary work files outside of the ebook work repo. 

It looks like you struggled a lot with the ToC while working on the ebook. In the future, just save it for last - `se build-toc` will always generate the right ToC assuming your final ebook structure is correct. You should almost never have to manually edit the ToC.

**Comment by atharva7-g** [comment]
Okay, thanks! Should I commit all of this into a single commit or go point-by-point?


> Your git history contains a lot of commits, changes, and deletions of temporary files, like readmes and lint.txt. ...

Should I just delete these commits and the ToC ones also?

**Comment by acabal** [comment]
You can break it up into small commits. Commits are free and the more isolated they are, the easier it is to reason about the history.

If you can delete those commits without affecting the rest of the history, then go for it! That would be helpful.

**Comment by atharva7-g** [comment]
> honoured above every one should be everyone

Should this be an editorial commit?

**Comment by acabal** [comment]
Yes, because we're changing spelling.

Remember that each small distinct unit of work should be its own commit. Don't roll up a bunch of different unrelated things into a single commit, because if we want to edit the commit or change the message in the future, it will be impossible to unravel.

**Comment by acabal** [comment]
Hi there, are you still making progress on these issues? Please keep us updated. Thanks!

**Comment by atharva7-g** [comment]
Right, sorry. I was just converting `<i>` to `<em>` tags, what should I wrap nota bene with?

And, yes, mostly everything else seems to be done from my side.

**Comment by acabal** [comment]
Since it's a common phrase in M-W you can remove italics entirely.

**Comment by atharva7-g** [comment]
And what about "⸻ Gazette" and "bon vivant"?

**Comment by acabal** [comment]
--- Gazette should be italicized because it's a newspaper. Bon vivant is in MW and so doesn't need italics. See the manual for rules on what to italicize and when.

**Comment by atharva7-g** [comment]
I have pushed the changes that were needed. Should I go ahead and try deleting the commits and clean up the repository a little?

**Comment by acabal** [comment]
If you want to clean up the history and you're confident you can do it without screwing up the repo, then go for it.

Please remember that individual commits should be small independent units of work. Each commit should address a single thing, and not mix several different kinds of changes together.

**Comment by atharva7-g** [comment]
So, I was able to delete the commits in a private repo, but we would end up losing the timeline of when the commits were made, that is, on what date, at what time, etc. Would that be fine? Or should I leave the commits there?

**Comment by acabal** [comment]
The actual dates and times don't matter that much. As long as the history is clean and orderly, with individual commits being single logical units of work.

**Comment by atharva7-g** [comment]
Okay, I will go ahead and delete the ~3 commits I identified. I suppose if something does go wrong, I will have a backup which I can push to a different repo.

**Comment by atharva7-g** [comment]
Yep, done, got rid of 6 commits, reworded a few, still have a backup just in case. Let me know if anything else is left.

**Comment by acabal** [comment]
Can you run `se clean`, then `se lint`, and correct any errors it finds?

**Comment by atharva7-g** [comment]
Sorry, think I messed up in the merge conflicts, think it should be fine now. Also ran semanticate, typogrify, and modernize-spelling, no errors.

**Comment by acabal** [comment]
Can you do a diff against your backup copy to make sure the final repos are identical after the rebase?

**Comment by atharva7-g** [comment]
Yep, everything is fine from what I can see. The only difference is in local.css, but I suppose the version in this repo is the correct one.

**Comment by atharva7-g** [comment]
So, is there anything left now?

**Comment by acabal** [comment]
Did you run lint again? I'm still getting errors. `CONTRIBUTOR_FULL_NAME` needs to be set or the element removed if the full name is the same as the pen name. The long description is not escaped HTML, see the manual. And several loan words are italicized when they should no longer be. Please run `se lint` and fix anything it alerts you to.

**Comment by atharva7-g** [comment]
Whelp, fixed. 
But I am also getting `File does not match` errors. Should I copy the files from the pipx folder to the repo folder and push?

**Comment by acabal** [comment]
Yes, if the files in question have been updated since the last toolset version then you can simply copy them in.

**Comment by atharva7-g** [comment]
Pushed. Also ran lint again, and ran typogrify, modernize spelling, semanticate.

Anything else which would be left?

**Comment by atharva7-g** [comment]
So...? Any updates?

**Comment by acabal** [comment]
This was released over a week ago, did you not get an email from the mailing list?

**Comment by atharva7-g** [comment]
Oh, whelp, I think I missed it. Anyway, glad to know it's up on the web!
